# Prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Status bar
set -g status-bg black
set -g status-fg green
set -g status-style bold
set -g window-status-current-style fg=yellow,bg=blue,bold
set -g window-status-current-format " #I:#W "
set -g window-status-style fg=white,bg=black
set -g window-status-format " #I:#W "
set -g status-right "%Y-%m-%d %H:%M:%S"

# Panes and Windows
set-option -g base-index 1
setw -g pane-base-index 1
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -n M-Left previous-window
bind -n M-Right next-window
set-option -g renumber-windows on

# History and Mouse
set -g history-limit 10000
set -g mouse on
set -g aggressive-resize on

# Copy mode (vi-style + wl-copy)
setw -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# Utils
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
bind-key C-a last-window
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1
bind-key x kill-pane

# Storage session
bind s move-window -t s:
new-session -d -s s
bind-key Tab switch-client -l
